### ISSUE TITLE
Can't Access Signature Gene sets

### ISSUE THREAD

**Issue by SickMcNugget** [azizilab/starfysh#13]
Hi, I am trying to run the colab tutorial at the moment, and I am unable to access the signature gene sets through the provided link. Google Drive simply says that the file does not exist.

I'm unsure whether this is an error in the link: https://drive.google.com/file/d/1yAfAj7PaFJZph88MwhWNXL5Kx5dKMngZ/view?usp=share_link

**Comment by YinuoJin** [comment]
Hi,

Sorry for the delayed reply!  Our colab tutorial is a bit outdated and currently under modifications. Please kindly find the signature links via either our updated tutorial: https://starfysh.readthedocs.io/en/latest/notebooks/Starfysh_tutorial_real.html, or our github main page (section `Model I/O`). Thanks!
