### ISSUE TITLE
bug in find_archettypal_spots when major=True

### ISSUE THREAD

**Issue by mjhubisz** [azizilab/starfysh#23]
I have been going through the Starfysh_tutorial_real.ipynb and find it always crashes in this optional code block for when gene signatures aren't provided:
```
aa_model = AA.ArchetypalAnalysis(adata_orig=adata_normed)
archetype, arche_dict, major_idx, evs = aa_model.compute_archetypes(r=40)

# (1). Find archetypal spots & archetypal clusters
arche_df = aa_model.find_archetypal_spots(major=True)

# (2). Define "signature genes" as marker genes associated with each archetypal cluster
gene_sig = aa_model.find_markers(n_markers=30, display=False)
gene_sig.head()
```

It crashes in the find_markers function (with IndexError: index 1172 is out of bounds for axis 0 with size 1162), but I believe the error is in find_archetypal_spots. The arche_df object contains values as high as 1172, whereas aa_model.n_spots=1162. If I run find_archetypal_spots as above, but with major=False, then the max value of arche_df is 1161 as expected, and the remaining code runs fine. I've looked through the underlying code a bit and think there is an indexing error in find_archetypal_spots or get_knns (which it calls) but have not quite pinpointed it. Thanks.

**Comment by YinuoJin** [comment]
Hi,

Thanks for reaching out to us and apologies for the inconvenience. We just updated the latest tutorial notebooks for real data consistent with the up-to-date Starfysh package under the `notebooks` repository. In the meanwhile, please install / re-install starfysh locally: cloning the repo & use `setup.py`. We're working on new release via pip right now.

Please don't hesitate to reach out if you still see the error! Thanks in advance.

**Comment by mjhubisz** [comment]
Thanks for the response and sorry for slow reply, haven't had time to turn back to this. I installed the github version of starfysh and used the notebooks in the notebook repository and everything is running smoothly.
