### ISSUE TITLE
Xenium data

### ISSUE THREAD

**Issue by Bo-UT** [azizilab/starfysh#24]
Hi, 

Thanks for the great tools. I am wondering if Starfysh is also working for Xenium data analysis? It would be of great help if there is a tutorial to perform spatial analysis on Xenium data. 
Thanks a lot. 

Bo

**Comment by YinuoJin** [comment]
Hi Bo,

Thanks for reaching out! Starfysh is compatible with multi-cell resolution ST datasets such as Visium, Slide-seq, etc.. While we notice the increasing interest in Xenium, the platform provides single-cell resolution and doesn't fit into the current Starfysh usage (deconvolution & downstream analysis). 

We recommend checking 10X github repositories or reach out to Janesick et al., (2021). We'll also notify users if we decide to include Xenium integration in the future.

Best,
Yinuo
