### ISSUE TITLE
starfysh/AA.py:230   IndexError: index 1172 is out of bounds for axis 0 with size 1162

### ISSUE THREAD

**Issue by Xxianna** [azizilab/starfysh#32]
-03-28 21:32:23]Computing intrinsic dimension to estimate k...
-03-28 21:32:23]Estimating lower bound of # archetype as 9...
30 components are retained using conditional_number=30.00
-03-28 21:32:52]Calculating UMAPs for counts + Archetypes...
-03-28 21:32:54]Calculating UMAPs for counts + Archetypes...
-03-28 21:32:57]0.7599 variance explained by raw archetypes.
Merging raw archetypes within 20 NNs to get major archetypes
-03-28 21:32:57]Finding 20 nearest neighbors for each archetype...
-03-28 21:32:57]Finding 30 top marker genes for each archetype...
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[21], line 8
      5 arche_df = aa_model.find_archetypal_spots(major=True)
      7 # (2). Find marker genes associated with each archetypal cluster
----> 8 markers_df = aa_model.find_markers(display=False)
     10 # (3). Map archetypes to closest anchors within `r` nearest neighbors
     11 # Choose the top 5% anchors of each cell type for mapping
     12 percent_anchor = 0.05

File ~/miniconda3/envs/bioinfo_env/lib/python3.10/site-packages/starfysh/AA.py:230, in ArchetypalAnalysis.find_markers(self, n_markers, display)
    227 for col in self.arche_df.columns:
    228     # Annotate in-group (current archetype) vs. out-of-group
    229     annots = np.zeros(self.n_spots, dtype=np.int64).astype(str)
--> 230     annots[self.arche_df[col]] = col
    231     adata.obs[col] = annots
    232     adata.obs[col] = adata.obs[col].astype('category')

IndexError: index 1172 is out of bounds for axis 0 with size 1162

# while I'm running
# Starfysh_tutorial_real.ipynb

aa_model = AA.ArchetypalAnalysis(adata_orig=adata_normed)
archetype, arche_dict, major_idx, evs = aa_model.compute_archetypes()

#(1). Find archetypal spots & archetypal clusters
arche_df = aa_model.find_archetypal_spots(major=True)

#(2). Find marker genes associated with each archetypal cluster
markers_df = aa_model.find_markers(display=False)

#(3). Map archetypes to closest anchors within `r` nearest neighbors
#Choose the top 5% anchors of each cell type for mapping
percent_anchor = 0.05
n_ancs = int(percent_anchor*adata.shape[0])

anchors_df = visium_args.get_anchors()
map_df, map_dict = aa_model.assign_archetypes(anchor_df=anchors_df[:n_ancs],
                                              r=n_ancs)

**Comment by YinuoJin** [comment]
H, thanks for using Starfysh and reaching out.

The global pip installation is outdated (we're working to update very soon). Can you try cloning the github version with local installation? Thanks in advance!
