### ISSUE TITLE
A more complete tutorial is needed

### ISSUE THREAD

**Issue by Lings01** [azizilab/starfysh#35]
I found that v1.1.1 have data integration function

**Comment by siyuh** [comment]
Hi, thank you for your interest in our model. We have updated the tutorial with the integration function. 

Is https://github.com/azizilab/starfysh/blob/main/notebooks/Starfysh_tutorial_integration.ipynb what you need?

**Comment by Lings01** [comment]
> Hi, thank you for your interest in our model. We have updated the tutorial with the integration function. 
> 
> 
> 
> Is https://github.com/azizilab/starfysh/blob/main/notebooks/Starfysh_tutorial_integration.ipynb what you need?  

That's what I need. Thank you so much!
