### ISSUE TITLE
ERROR: Cannot install large-image and large-image[sources]==1.0.0 because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by ansonkn** [azizilab/starfysh#37]
Thank you for creating this intereseting tool! 

I have been struggling to install Starfysh following the installation guide. I get the conflicting below.

ERROR: Cannot install large-image and large-image[sources]==1.0.0 because these package versions have conflicting dependencies.

I have tried different version of python and within virtual environments. Any help would be greatly appreciated.

**Comment by YinuoJin** [comment]
Hi ansonkn,

Thanks for reaching out and for using Starfysh! We've noticed the "large-image" relevant installation issues. Wondering whether the following command might work for you: `pip install histomicstk --find-links https://girder.github.io/large_image_wheels`?

**Comment by ansonkn** [comment]
Thank you Yinuo, the suggested install worked! Thank you for your quick response.
