### ISSUE TITLE
Data availability

### ISSUE THREAD

**Issue by elliewith** [azizilab/starfysh#4]
Hi, Thank you for the very useful tool. Where can I find the spatial transcriptomic data used (or if not available do you have a rough date for when it will be?) Thanks!

**Comment by siyuh** [comment]
Hi, thank you for your interest in our tool!!

Please refer to two of the public datasets we used in the preprint:

The public dataset from Wu et al. could be accessed from the Zenodo data repository (https://doi.org/10.5281/zenodo.4739739). The public dataset from Andersson et al. can be downloaded from the Zenodo data repository (https://doi.org/10.5281/zenodo.3957257).

We are working on a few more tutorials addressing the novelty of Starfysh, including the toy datasets. Will probably have some updates this weekend. Stay tuned :)

**Comment by elliewith** [comment]
Thanks for the quick response :) In the paper it seems like you have new dataset as well, and I was wondering whether these will be publicly available at some point? Apologies if this is not the case and I am mistaken!

**Comment by siyuh** [comment]
No worries! the new datasets will be available after the preprint is published 😊
