### ISSUE TITLE
Error when using 'utils_integrate.run_starfysh'

### ISSUE THREAD

**Issue by yao50985098** [azizilab/starfysh#40]
Thank you for the nice tool!
I was trying to integrate ST Visium data, and all the previous steps went well until I got this error at the model training step.
![截屏2024-04-18 23 20 07](https://github.com/azizilab/starfysh/assets/44132948/5b5df321-59b7-4ef9-b0a2-133d8b84b88a)

![截屏2024-04-18 23 23 35](https://github.com/azizilab/starfysh/assets/44132948/2b73c437-3375-49f1-a59e-8827f524ef1f)

[2024-04-18 22:36:37] Running Starfysh with 1 restarts, choose the model with best parameters...
[2024-04-18 22:36:37]  ===  Restart Starfysh 1 === 

[2024-04-18 22:36:37] Initializing model parameters...
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[26], line 5
      3 device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
      4 ###
----> 5 model, loss = utils_integrate.run_starfysh(integrated_args,
      6                                            n_repeats=n_repeats,
      7                                            epochs=epochs,
      8                                            poe=True,
      9                                            device=device
     10                                           )
     11 # Save model
     12 #torch.save(model.state_dict(), os.path.join(data_path, 'integ_model.pt'))

File ~/miniconda3/envs/stlearn/lib/python3.8/site-packages/starfysh/utils_integrate.py:480, in run_starfysh(visium_args, n_repeats, lr, epochs, batch_size, alpha_mul, poe, device, verbose)
    477 scheduler = optim.lr_scheduler.ExponentialLR(optimizer, gamma=0.99)
    479 for epoch in range(epochs):
--> 480     result = train_func(model, trainloader, device, optimizer)
    481     torch.cuda.empty_cache()
    483     loss_tot, loss_reconst, loss_u, loss_z, loss_c, loss_n, corr_list = result

File ~/miniconda3/envs/stlearn/lib/python3.8/site-packages/starfysh/starfysh.py:821, in train_poe(model, dataloader, device, optimizer)
    819 inference_outputs = model.inference(x)  # inference for 1D expr. data
    820 generative_outputs = model.generative(inference_outputs, xs_k)
--> 821 img_outputs = model.predictor_img(img)  # inference & generative for 2D img. data
    822 poe_outputs = model.predictor_poe(inference_outputs, img_outputs)  # PoE generative outputs
    824 # Check for NaNs

File ~/miniconda3/envs/stlearn/lib/python3.8/site-packages/starfysh/starfysh.py:507, in AVAE_PoE.predictor_img(self, y)
    504 y_n = torch.log1p(y)
    506 # q(z | y)
--> 507 hidden_z = self.img_z_enc(y_n)
    508 qz_m = self.img_z_enc_m(hidden_z)
    509 qz_logv = self.img_z_enc_logv(hidden_z)

File ~/miniconda3/envs/stlearn/lib/python3.8/site-packages/torch/nn/modules/module.py:1511, in Module._wrapped_call_impl(self, *args, **kwargs)
   1509     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1510 else:
-> 1511     return self._call_impl(*args, **kwargs)

File ~/miniconda3/envs/stlearn/lib/python3.8/site-packages/torch/nn/modules/module.py:1520, in Module._call_impl(self, *args, **kwargs)
   1515 # If we don't have any hooks, we want to skip the rest of the logic in
   1516 # this function, and just call forward.
   1517 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1518         or _global_backward_pre_hooks or _global_backward_hooks
   1519         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1520     return forward_call(*args, **kwargs)
   1522 try:
   1523     result = None

File ~/miniconda3/envs/stlearn/lib/python3.8/site-packages/torch/nn/modules/container.py:217, in Sequential.forward(self, input)
    215 def forward(self, input):
    216     for module in self:
--> 217         input = module(input)
    218     return input

File ~/miniconda3/envs/stlearn/lib/python3.8/site-packages/torch/nn/modules/module.py:1511, in Module._wrapped_call_impl(self, *args, **kwargs)
   1509     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1510 else:
-> 1511     return self._call_impl(*args, **kwargs)

File ~/miniconda3/envs/stlearn/lib/python3.8/site-packages/torch/nn/modules/module.py:1520, in Module._call_impl(self, *args, **kwargs)
   1515 # If we don't have any hooks, we want to skip the rest of the logic in
   1516 # this function, and just call forward.
   1517 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1518         or _global_backward_pre_hooks or _global_backward_hooks
   1519         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1520     return forward_call(*args, **kwargs)
   1522 try:
   1523     result = None

File ~/miniconda3/envs/stlearn/lib/python3.8/site-packages/torch/nn/modules/linear.py:116, in Linear.forward(self, input)
    115 def forward(self, input: Tensor) -> Tensor:
--> 116     return F.linear(input, self.weight, self.bias)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (32x2028 and 676x256)

Currently, I can not solve this issue. Looking forward for your help. Thank you!

**Comment by YinuoJin** [comment]
Hi yao50985098,

Thanks for using Starfysh and reaching out! I'm wondering whether you were using your own data or our example data for integration. I'm trying to figure out what's the best way to reproduce your error. Thanks in advance.

Best,
Yinuo
