### ISSUE TITLE
advice for making a custom signature matrix

### ISSUE THREAD

**Issue by inofechm** [azizilab/starfysh#42]
Hello I am interested in using starfysh on a large number of visium datasets.
I have lots of scRNA seq of high resolution cell types and want to deconvulute the spatial data for the same resolution.
I don't think the archetypal method for getting signatures will line up exactly with my finely grained cell types and as such I want to use a custom signature matrix, similar to the at described in the tutorial.
I was wondering if you could please provide some advice regarding how to define signatures especially between related cell types such as subtypes of CD8 T cells. 

Should I just use all genes that fit a certain fold change cutoff in DGE analysis from the scRNA seq, should I use genes that are the most specific to each cell type? If two cell types like subtypes of macrophages have some shared genes that separate them from other cell types but not each other should I include those?

Thank you,
Ido

**Comment by YinuoJin** [comment]
Hi Ido,

Thanks for reaching out! We constructed the sample signature matrix through literature search and help from our clinician collaborators. For your question of refined cell-state deconvolution, I recommend starting with canonical signatures (if known), and maybe try a rigorous logFC cutoff from DGE analysis. Although we've shown robustness against various length of signatures, low overlap ratio between 2 closely-related cell states would generally result in better deconvolution separation. 

Best,
Yinuo

**Comment by inofechm** [comment]
Thanks for the quick response, I will take this into consideration!
