### ISSUE TITLE
Potential Bug in `IntegrativeDataset`

### ISSUE THREAD

**Issue by schae211** [azizilab/starfysh#44]
If I understand the code correctly `IntegrativeDataset` is actually used if we run the model without H&E image so `self.image` can/should be `None` (in contrast to `IntegrativePoEDataset` where indeed self.image should not be `None`. 
These are the lines I am referring to:
https://github.com/azizilab/starfysh/blob/7407267515d56a7dc96672c764a40635fae581d6/starfysh/dataloader.py#L113-L132

**Comment by YinuoJin** [comment]
Hi schae211,

Yes you're right thanks for the the reminder. Running without histology integration (PoE) indeed doesn't require the paired image. By default we load the image metadata anyway so the assertion error doesn't get triggered. We will update the code.
