### ISSUE TITLE
Spots without deconvolution output?

### ISSUE THREAD

**Issue by kuchikachi** [azizilab/starfysh#47]
In some cases the spot number of output is not the size as the input. Might there be any spot without output?

**Comment by YinuoJin** [comment]
Hi @kuchikachi 

Can you elaborate with some example(s), preferable with logs or error messages? I'll try to reproduce your case to make sure whether it's a bug in our code or from preprocessing (e.g. removing low-quality spots). Thanks in advance.

**Comment by siyuh** [comment]
technically, I think it should not be the case since we didn't have spot filtering.
