### ISSUE TITLE
Feature request: enhance plot_spatial_gene

### ISSUE THREAD

**Issue by Jorges1000** [azizilab/starfysh#49]
Hi, it would be great to be able to add point_size and scale (log vs linear, etc) to plot_spatial_gene function. Tried to change the figsize to no avail.

Thanks!

**Comment by YinuoJin** [comment]
Thanks for the suggestion, we'll try to incorporate it in the next released version.

**Comment by siyuh** [comment]
Hi, we have updated the plot function; please check the updates in github. Please install our new version and check our tutorial for details in the following days. Thanks!
