### ISSUE TITLE
Question about the calculation of the prior distribution of z

### ISSUE THREAD

**Issue by Enderlogic** [azizilab/starfysh#56]
Hi,

Thank you for maintaining this great package. I noticed that in your code, you calculate the mean and variance of the prior distribution of z, i.e., p(z|c,u) by the posterior rather than the prior of c and u. Is this a bug or a feature of your model? If it is the latter, could you please clarify its motivation? Thank you.

**Comment by YinuoJin** [comment]
Hi @Enderlogic 

Thanks for reaching out. To answer your question in high level, yes we need to do Monte Carlo sampling to get q(u) & q(c). The main reason is that our model is a hierarchical VAE, so we need to do so for maintaining the structure between {u, c} - {z}. Please refer to the ELBO equation on page 15 of our paper (you'll notice the difference between KL divergence terms).

Similar examples could be found in other laddar VAE literatures: e.g. equation (1) [here](https://proceedings.neurips.cc/paper/2020/file/e3b21256183cf7c2c7a66be163579d37-Paper.pdf) & equation (6) [here](https://arxiv.org/pdf/1709.07902)

**Comment by Enderlogic** [comment]
Thank you for your explanation and the relevant papers. If I understand correctly, both u and σ in the prior of z are some sort of unknown "hyperparameters" that need to be learned and updated during training. If so, why do you only assign u a prior but not σ?

**Comment by YinuoJin** [comment]
Hi, thanks for the follow up. Following the plate model of Starfysh, u and $\sigma$ both represent cell-state information: we define u to represent low-dim cell-state mechanics and $\sigma$ for allowing cell-state specific heterogeneity.

Commonly u is more important than $\sigma$ for differentiating one cell type/state from another. Therefore we designed u as a "random variable" and $\sigma$ as a global parameter that could be learnt during optimization. None of them are hyperparameters, which should be fixed quantities for the model. Of course you can always design additional priors and "hyper-priors" for random variables, but in Starfysh we opted to have a balance between setting priors and learning from the data. Hope it helps!
