### ISSUE TITLE
Unable to Install Github Version of Starfysh on to HPC

### ISSUE THREAD

**Issue by alexprystupa** [azizilab/starfysh#57]
Hi! Thank you so much for your wonderful package! I am very excited to give it a try. I have previously been able to install it via making a conda environment and doing pip install starfysh, but as noted in other github issues, the histology integration only works if using the github latest version. I cannot seem to install the git version into a conda env on my HPC. 

First I created a conda environment, install git and pip using conda install git pip, cloned the github directory and cd and pip install . as per instructions:

1. Output of installation process
  
[starfysh_git_install_outs_1.txt](https://github.com/user-attachments/files/17132515/starfysh_git_install_outs_1.txt)

I then installed gdal=3.9.2 with conda install gdal=3.9.2 directly to attempt to fix the gdal error.

2. Output of conda list after gdal installation

[starfysh_git_conda_list_post_gdal_3.9.2_install.txt](https://github.com/user-attachments/files/17132534/starfysh_git_conda_list_post_gdal_3.9.2_install.txt)

Next I tried reinstalling with pip install . again.

3. Output of pip install . post gdal installation
[starfysh_git_install_outs_2.txt](https://github.com/user-attachments/files/17132548/starfysh_git_install_outs_2.txt)

4. Output of conda list post gdal installation

[starfysh_git_conda_list_post_second_install_attempt.txt](https://github.com/user-attachments/files/17132551/starfysh_git_conda_list_post_second_install_attempt.txt)

I am currently stuck at this point as nothing I can do can resolve these dependency conflicts. Any help would be greatly appreciated. Thank you again for this great package!

**Comment by YinuoJin** [comment]
Hi @alexprystupa,

Thanks for the interest in using Starfysh! Yes we noticed that a large proportion of user-reported installation errors come from the `histomicstk` package. From reading the installation log [starfysh_git_install_outs_2.txt](https://github.com/user-attachments/files/17132548/starfysh_git_install_outs_2.txt), the error comes from `mapnik`.

Some potential suggestions if could help: (1). I usually use `pip install` instead of `conda` due to its long (and sometimes unnecessary) version searching; this way allows specific fixes to version conflicts (2). Can you try `pip install large-image-source-mapnik` after doing `pip install . ` from the Starfysh github version? (3). If all of them don't work, I can try reproducing your environment on our HPC.

**Comment by alexprystupa** [comment]
Hi, thank you so much for the quick response. I end up receiving the same exact errors as before when trying what you suggested. 

Interestingly, I have been able to successfully install the github version of starfysh locally. I am not sure why I am able to do it locally but not on the HPC. However, I need it installed on the HPC because the Histology integration requires more computational resources than my local computer has. I am attaching the conda list output of the successful location installation. I am not sure how to proceed from here. Thank you!

[starfysh_local_installation_conda_list.txt](https://github.com/user-attachments/files/17215512/starfysh_local_installation_conda_list.txt)

**Comment by YinuoJin** [comment]
Sorry for hearing that. I'll try to test the installation on our HPC this week. Will get back to you ASAP after the remote test.

**Comment by YinuoJin** [comment]
Hi @alexprystupa,

I had a test to our HPC server last week. Despite various warnings regarding `histomicstk` and `gdal` versions, the installation was successful with `cuda11.8`. The command to our HPC is `module load cuda11.8/toolkit`. I'm not sure if it's similar for reproducing the environment on your end, but I'll try to do some modifications on setting the problematic packages as optional.
